import { AppData } from './types';

export const defaultData: AppData = {
  fichesPoste: [
    { id: '1', intitule: "Chef d'équipe production", rattachement: 'Directeur de production', mission: "Superviser l'équipe de production et garantir l'atteinte des objectifs journaliers", activites: "Planification des tâches, suivi qualité, gestion des équipes, reporting", competences: "Leadership, gestion d'équipe, connaissance des process agroalimentaires", diplome: "BTS/Licence en agroalimentaire ou équivalent, 3 ans d'expérience", horaires: '06h00 - 14h00 / 14h00 - 22h00', indicateur: "Taux d'atteinte des objectifs de production" },
    { id: '2', intitule: 'Opérateur de production', rattachement: "Chef d'équipe production", mission: 'Assurer les opérations de transformation sur la ligne de production', activites: "Conduite de machines, contrôle visuel, nettoyage, respect des consignes d'hygiène", competences: 'Rigueur, dextérité, connaissance HACCP', diplome: 'CAP/BEP ou expérience en usine agroalimentaire', horaires: '06h00 - 14h00 / 14h00 - 22h00', indicateur: 'Rendement horaire et taux de rebut' },
    { id: '3', intitule: 'Agent de contrôle qualité', rattachement: 'Responsable qualité', mission: 'Contrôler la conformité des matières premières et produits finis', activites: "Prélèvements, analyses, rédaction de rapports, gestion des non-conformités", competences: 'Analyse sensorielle, métrologie, normes ISO/HACCP', diplome: "DUT/Licence en biologie, chimie ou agroalimentaire", horaires: '07h00 - 16h00', indicateur: 'Taux de conformité des lots contrôlés' },
    { id: '4', intitule: 'Magasinier', rattachement: 'Responsable logistique', mission: 'Gérer les entrées/sorties de stock et organiser le magasin', activites: "Réception, rangement, préparation des commandes, inventaire", competences: 'Organisation, maîtrise des outils de gestion de stock', diplome: 'Bac+2 en logistique ou expérience équivalente', horaires: '07h00 - 16h00', indicateur: 'Exactitude des inventaires et délai de préparation' },
    { id: '5', intitule: 'Agent administratif / RH', rattachement: 'Directeur général', mission: "Gérer l'administration du personnel et le suivi RH", activites: "Paie, contrats, absences, recrutement, dossiers du personnel", competences: 'Droit du travail camerounais, Excel, discrétion', diplome: "Licence en GRH, droit ou gestion", horaires: '08h00 - 17h00', indicateur: 'Délai de traitement des dossiers RH' },
    { id: '6', intitule: 'Agent de maintenance', rattachement: 'Responsable technique', mission: 'Assurer la maintenance préventive et curative des équipements', activites: "Diagnostic de pannes, réparations, maintenance préventive, gestion des pièces", competences: 'Électromécanique, pneumatique, lecture de schémas', diplome: "BTS en maintenance industrielle ou électromécanique", horaires: '07h00 - 16h00 + astreintes', indicateur: 'Taux de disponibilité des machines' },
  ],
  procedures: [
    {
      id: 'proc1', nom: 'Réception des matières premières', date: new Date().toISOString().slice(0, 10),
      type: 'entree' as const, creePar: 'Chef de site', statut: 'en_cours' as const, notes: '',
      items: [
        { id: 'p1i1', label: 'Vérifier le bon de livraison', checked: false },
        { id: 'p1i2', label: 'Contrôler la température du camion', checked: false },
        { id: 'p1i3', label: 'Inspecter visuellement les emballages', checked: false },
        { id: 'p1i4', label: 'Prélever un échantillon pour analyse', checked: false },
        { id: 'p1i5', label: 'Peser les marchandises reçues', checked: false },
        { id: 'p1i6', label: 'Enregistrer dans le système de stock', checked: false },
        { id: 'p1i7', label: 'Ranger dans la zone de stockage appropriée', checked: false },
      ]
    },
    {
      id: 'proc2', nom: 'Contrôle qualité', date: new Date().toISOString().slice(0, 10),
      type: 'controle' as const, creePar: 'Chef de site', statut: 'en_cours' as const, notes: '',
      items: [
        { id: 'p2i1', label: 'Prélever les échantillons sur la ligne', checked: false },
        { id: 'p2i2', label: 'Vérifier pH et acidité', checked: false },
        { id: 'p2i3', label: 'Contrôler la texture et la couleur', checked: false },
        { id: 'p2i4', label: 'Test microbiologique rapide', checked: false },
        { id: 'p2i5', label: 'Vérifier les dates et le marquage', checked: false },
        { id: 'p2i6', label: 'Remplir le registre de contrôle', checked: false },
      ]
    },
    {
      id: 'proc3', nom: 'Sortie des produits finis', date: new Date().toISOString().slice(0, 10),
      type: 'sortie' as const, creePar: 'Chef de site', statut: 'en_cours' as const, notes: '',
      items: [
        { id: 'p3i1', label: 'Vérifier le bon de commande', checked: false },
        { id: 'p3i2', label: 'Contrôler les quantités préparées', checked: false },
        { id: 'p3i3', label: "Vérifier l'étiquetage et les DLC", checked: false },
        { id: 'p3i4', label: 'Contrôler la température de stockage', checked: false },
        { id: 'p3i5', label: 'Charger et sceller le véhicule', checked: false },
        { id: 'p3i6', label: 'Émettre le bon de livraison', checked: false },
      ]
    },
  ],
  stocks: [
    { id: 's1', reference: 'EMB-GS-001', designation: 'Emballage grillée et salée', unite: 'paquet', categorie: 'emballages', seuilAlerte: 50 },
    { id: 's2', reference: 'EMB-CAR-001', designation: 'Emballage arachide caramélisée', unite: 'paquet', categorie: 'emballages', seuilAlerte: 50 },
    { id: 's3', reference: 'EMB-ETQ-001', designation: 'Étiquette farine de plantain', unite: 'rouleau', categorie: 'emballages', seuilAlerte: 5 },
    { id: 's4', reference: 'EMB-SAC-001', designation: 'Sac plastique farine de plantain', unite: 'paquet', categorie: 'emballages', seuilAlerte: 10 },
    { id: 's5', reference: 'CON-GAN-001', designation: 'Gants', unite: 'paquet', categorie: 'emballages', seuilAlerte: 2 },
    { id: 's6', reference: 'CON-MSQ-001', designation: 'Cache-nez', unite: 'paquet', categorie: 'emballages', seuilAlerte: 2 },
    { id: 's7', reference: 'CON-SAV-001', designation: 'Savon liquide', unite: 'L', categorie: 'emballages', seuilAlerte: 3 },
    { id: 's8', reference: 'CON-CHA-001', designation: 'Charlotte à cheveux jetable', unite: 'paquet', categorie: 'emballages', seuilAlerte: 2 },
    { id: 's9', reference: 'EMB-PAP-001', designation: 'Papier emballage arachide', unite: 'rouleau', categorie: 'emballages', seuilAlerte: 3 },
    { id: 's10', reference: 'CON-JAV-001', designation: 'Eau de javel', unite: 'L', categorie: 'emballages', seuilAlerte: 5 },
    { id: 's11', reference: 'CON-PAP-001', designation: 'Papier emballage A4', unite: 'paquet', categorie: 'emballages', seuilAlerte: 2 },
    { id: 's12', reference: 'MP-ARA-001', designation: 'Arachides crues décortiquées', unite: 'kg', categorie: 'mp_arachides', seuilAlerte: 500 },
    { id: 's13', reference: 'MP-ARA-002', designation: 'Arachides grillées', unite: 'kg', categorie: 'mp_arachides', seuilAlerte: 300 },
    { id: 's14', reference: 'MP-PLA-001', designation: 'Plantain frais', unite: 'kg', categorie: 'mp_plantain', seuilAlerte: 400 },
    { id: 's15', reference: 'MP-SUC-001', designation: 'Sucre cristallisé', unite: 'kg', categorie: 'sucre', seuilAlerte: 200 },
    { id: 's16', reference: 'PF-FPL-001', designation: 'Farine de plantain (sceau)', unite: 'sceau', categorie: 'pf_farine_plantain', seuilAlerte: 30 },
    { id: 's17', reference: 'PF-GS-001', designation: 'Arachide grillée salée 350g', unite: 'unité', categorie: 'pf_nature', seuilAlerte: 100 },
    { id: 's18', reference: 'PF-CAR-001', designation: 'Arachide caramélisée 250g', unite: 'unité', categorie: 'pf_caramelisees', seuilAlerte: 100 },
    { id: 's19', reference: 'EMB-CAR-002', designation: 'Cartons', unite: 'unité', categorie: 'emballages', seuilAlerte: 20 },
  ],
  lots: [
    { id: 'l1', articleId: 's1', quantite: 148, dlc: '2027-07-01', dateEntree: '2026-07-15', numero: 'LOT-EMB-001' },
    { id: 'l2', articleId: 's2', quantite: 3, dlc: '2027-07-01', dateEntree: '2026-07-15', numero: 'LOT-EMB-002' },
    { id: 'l3', articleId: 's3', quantite: 1, dlc: '2028-01-01', dateEntree: '2026-07-10', numero: 'LOT-ETQ-001' },
    { id: 'l4', articleId: 's4', quantite: 18, dlc: '2028-01-01', dateEntree: '2026-07-10', numero: 'LOT-SAC-001' },
    { id: 'l5', articleId: 's5', quantite: 0.5, dlc: '2027-12-01', dateEntree: '2026-07-20', numero: 'LOT-GAN-001' },
    { id: 'l6', articleId: 's6', quantite: 0.5, dlc: '2027-12-01', dateEntree: '2026-07-20', numero: 'LOT-MSQ-001' },
    { id: 'l7', articleId: 's7', quantite: 2, dlc: '2027-12-01', dateEntree: '2026-07-20', numero: 'LOT-SAV-001' },
    { id: 'l8', articleId: 's8', quantite: 0.5, dlc: '2027-12-01', dateEntree: '2026-07-20', numero: 'LOT-CHA-001' },
    { id: 'l9', articleId: 's9', quantite: 1, dlc: '2028-01-01', dateEntree: '2026-07-15', numero: 'LOT-PAP-001' },
    { id: 'l10', articleId: 's10', quantite: 5, dlc: '2027-06-01', dateEntree: '2026-07-10', numero: 'LOT-JAV-001' },
    { id: 'l11', articleId: 's11', quantite: 4, dlc: '2028-01-01', dateEntree: '2026-07-25', numero: 'LOT-A4-001' },
    { id: 'l12', articleId: 's12', quantite: 2500, dlc: '2026-10-15', dateEntree: '2026-07-01', numero: 'LOT-ARA-001' },
    { id: 'l13', articleId: 's12', quantite: 1000, dlc: '2026-12-01', dateEntree: '2026-07-28', numero: 'LOT-ARA-002' },
    { id: 'l14', articleId: 's14', quantite: 800, dlc: '2026-08-05', dateEntree: '2026-07-20', numero: 'LOT-PLA-001' },
    { id: 'l15', articleId: 's15', quantite: 180, dlc: '2027-06-01', dateEntree: '2026-07-10', numero: 'LOT-SUC-001' },
    { id: 'l16', articleId: 's16', quantite: 87, dlc: '2026-10-01', dateEntree: '2026-07-28', numero: 'LOT-FPL-001' },
  ],
  mouvements: [],
  fournisseurs: [
    { id: 'f1', nom: 'Coopérative Arachides Maroua', contact: '+237 6XX XX XX XX', zone: 'Extrême-Nord', matieres: ['s12', 's13'], role: 'principal' },
    { id: 'f2', nom: 'Planteurs de Njombé', contact: '+237 6XX XX XX XX', zone: 'Littoral', matieres: ['s14'], role: 'principal' },
    { id: 'f3', nom: 'SOSUCAM', contact: 'commercial@sosucam.cm', zone: 'Centre', matieres: ['s15'], role: 'principal' },
    { id: 'f4', nom: 'Fournisseur emballages', contact: '+237 6XX XX XX XX', zone: 'Douala', matieres: ['s1', 's2', 's4', 's19'], role: 'principal' },
    { id: 'f5', nom: 'Arachides du Nord', contact: '+237 6XX XX XX XX', zone: 'Nord', matieres: ['s12'], role: 'secondaire' },
    { id: 'f6', nom: 'Divers / Main d\'oeuvre', contact: '', zone: 'Douala', matieres: [], role: 'secondaire' },
  ],
  saisonnalites: [
    { id: 'sais1', matiere: 'Arachides', periodeHaute: 'Oct-Jan', periodeBasse: 'Avr-Juil', recommandation: 'achat_groupe', notes: 'Acheter en volume pendant la récolte Oct-Jan, constituer un stock tampon pour la période creuse' },
    { id: 'sais2', matiere: 'Plantain', periodeHaute: 'Sep-Déc', periodeBasse: 'Fév-Mai', recommandation: 'stock_tampon', notes: 'Disponibilité réduite en saison sèche, prévoir du séchage/chips pour lisser la production' },
    { id: 'sais3', matiere: 'Sucre', periodeHaute: 'Toute l\'année', periodeBasse: '—', recommandation: 'aucune', notes: 'Approvisionnement stable via SOSUCAM' },
  ],
  candidats: [],
  rapports: [],
  productions: [
    { id: 'pr1', date: '2026-07-28', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 500, realise: 480, pertes: 12, machine: 'Machine à griller', blocages: '' },
    { id: 'pr2', date: '2026-07-28', unite: 'arachide', produit: 'Pâte d\'arachide nature 500g', conditionnement: '500g', objectif: 300, realise: 290, pertes: 8, machine: 'Malaxeur', blocages: '' },
    { id: 'pr3', date: '2026-07-28', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 120, realise: 115, pertes: 3, machine: 'Moulin à sec', blocages: '' },
    { id: 'pr4', date: '2026-07-29', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 500, realise: 510, pertes: 10, machine: 'Machine à griller', blocages: '' },
    { id: 'pr5', date: '2026-07-29', unite: 'arachide', produit: 'Pâte d\'arachide caramélisée 250g', conditionnement: '250g', objectif: 250, realise: 240, pertes: 6, machine: 'Malaxeur', blocages: '' },
    { id: 'pr6', date: '2026-07-29', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 120, realise: 118, pertes: 2, machine: 'Moulin à sec', blocages: '' },
    { id: 'pr7', date: '2026-07-30', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 500, realise: 490, pertes: 15, machine: 'Machine à griller', blocages: '' },
    { id: 'pr8', date: '2026-07-30', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 120, realise: 100, pertes: 5, machine: 'Moulin à sec', blocages: 'Panne séchoir 1h' },
    { id: 'pr9', date: '2026-07-31', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 500, realise: 520, pertes: 8, machine: 'Machine à griller', blocages: '' },
    { id: 'pr10', date: '2026-07-31', unite: 'arachide', produit: 'Pâte d\'arachide caramélisée 250g', conditionnement: '250g', objectif: 250, realise: 255, pertes: 4, machine: 'Malaxeur', blocages: '' },
    { id: 'pr11', date: '2026-07-31', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 120, realise: 122, pertes: 2, machine: 'Moulin à sec', blocages: '' },
    { id: 'pr12', date: '2026-08-01', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 500, realise: 495, pertes: 10, machine: 'Machine à griller', blocages: '' },
    { id: 'pr13', date: '2026-08-01', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 120, realise: 120, pertes: 1, machine: 'Moulin à sec', blocages: '' },
    { id: 'pr14', date: '2026-08-02', unite: 'arachide', produit: 'Arachide salée 350g', conditionnement: '350g', objectif: 400, realise: 385, pertes: 10, machine: 'Machine à griller', blocages: '' },
    { id: 'pr15', date: '2026-08-02', unite: 'plantain', produit: 'Farine de plantain 4kg', conditionnement: '4kg', objectif: 80, realise: 82, pertes: 1, machine: 'Moulin à sec', blocages: '' },
  ],
  inventaires: [],
  achats: [
    { id: 'ac1', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 2500, montantTotal: 2500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Moto pour livrer 2 cartons' },
    { id: 'ac2', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 2000, montantTotal: 2000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Échantillon carbonate' },
    { id: 'ac3', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 1500, montantTotal: 1500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Transport' },
    { id: 'ac4', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'plantain', quantite: 1, prixUnitaire: 1500, montantTotal: 1500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Transport farine' },
    { id: 'ac5', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'plantain', quantite: 1, prixUnitaire: 8500, montantTotal: 8500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Farine' },
    { id: 'ac6', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 3500, montantTotal: 3500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Sol' },
    { id: 'ac7', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 1000, montantTotal: 1000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Déplacement maman Ariel' },
    { id: 'ac8', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 3000, montantTotal: 3000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Canon portail' },
    { id: 'ac9', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'plantain', quantite: 1, prixUnitaire: 1000, montantTotal: 1000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Farine de maïs' },
    { id: 'ac10', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 100, montantTotal: 100, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Briquet' },
    { id: 'ac11', date: '2026-07-27', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 1000, montantTotal: 1000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Crédit Com Brice' },
    { id: 'ac12', date: '2026-07-31', fournisseurId: 'f6', articleId: '', unite: 'arachide', quantite: 25, prixUnitaire: 200, montantTotal: 5000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: "Main d'oeuvre (25 bouteilles)" },
    { id: 'ac13', date: '2026-07-31', fournisseurId: 'f6', articleId: '', unite: 'arachide', quantite: 1, prixUnitaire: 1500, montantTotal: 1500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: 'Tamisage arachide' },
    { id: 'ac14', date: '2026-07-31', fournisseurId: 'f6', articleId: '', unite: 'commun', quantite: 1, prixUnitaire: 2500, montantTotal: 2500, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: "Main d'oeuvre magasin" },
    { id: 'ac15', date: '2026-07-31', fournisseurId: 'f6', articleId: '', unite: 'plantain', quantite: 1, prixUnitaire: 3000, montantTotal: 3000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: "Main d'oeuvre dépulpage" },
    { id: 'ac16', date: '2026-07-31', fournisseurId: 'f6', articleId: '', unite: 'plantain', quantite: 1, prixUnitaire: 2000, montantTotal: 2000, devise: 'FCFA', bonCommande: '', statut: 'paye', notes: "Main d'oeuvre dépulpage Sam" },
  ],
  configUnites: [
    {
      id: 'arachide',
      label: 'Unité Arachide',
      produits: [
        { nom: 'Arachide salée', conditionnement: 'Sachet', poids: '350g' },
        { nom: 'Pâte d\'arachide nature', conditionnement: 'Pot', poids: '500g' },
        { nom: 'Pâte d\'arachide caramélisée', conditionnement: 'Pot', poids: '250g' },
      ],
      machines: ['Machine à griller', 'Concasseuse', 'Malaxeur', 'Emballeuse arachide', 'Emballeuse carton', 'Balance'],
    },
    {
      id: 'plantain',
      label: 'Unité Plantain (Farine)',
      produits: [
        { nom: 'Farine de plantain', conditionnement: 'Sac', poids: '4kg' },
        { nom: 'Farine de plantain', conditionnement: 'Sachet', poids: '1kg' },
        { nom: 'Farine de plantain', conditionnement: 'Sachet', poids: '500g' },
      ],
      machines: ['Dépulpeuse', 'Moulin à sec', 'Embouteilleuse', 'Thermosoudeuse', 'Balance'],
    },
  ],
  employes: [
    { id: 'e1', nom: 'Jean-Pierre Mbarga', poste: "Chef d'équipe production", presences: {
      '2026-07-28': 'present', '2026-07-29': 'present', '2026-07-30': 'present', '2026-07-31': 'present', '2026-08-01': 'present', '2026-08-02': 'present',
    }, justifications: [] },
    { id: 'e2', nom: 'Marie-Claire Ondoa', poste: 'Opérateur de production', presences: {
      '2026-07-28': 'present', '2026-07-29': 'present', '2026-07-30': 'absent', '2026-07-31': 'present', '2026-08-01': 'present', '2026-08-02': 'present',
    }, justifications: [{ date: '2026-07-30', motif: 'Maladie', justifie: true, preuve: 'Certificat médical' }] },
    { id: 'e3', nom: 'Paul Nguema', poste: 'Agent de contrôle qualité', presences: {
      '2026-07-28': 'present', '2026-07-29': 'present', '2026-07-30': 'present', '2026-07-31': 'present', '2026-08-01': 'absent', '2026-08-02': 'present',
    }, justifications: [] },
    { id: 'e4', nom: 'Fatou Diallo', poste: 'Magasinier', presences: {
      '2026-07-28': 'present', '2026-07-29': 'present', '2026-07-30': 'present', '2026-07-31': 'present', '2026-08-01': 'present', '2026-08-02': 'conge',
    }, justifications: [] },
    { id: 'e5', nom: 'Brigitte Ngo Biyong', poste: 'Agent administratif / RH', presences: {
      '2026-07-28': 'present', '2026-07-29': 'present', '2026-07-30': 'present', '2026-07-31': 'conge', '2026-08-01': 'conge', '2026-08-02': 'present',
    }, justifications: [] },
    { id: 'e6', nom: 'Samuel Ekotto', poste: 'Agent de maintenance', presences: {
      '2026-07-28': 'present', '2026-07-29': 'absent', '2026-07-30': 'present', '2026-07-31': 'present', '2026-08-01': 'present', '2026-08-02': 'present',
    }, justifications: [{ date: '2026-07-29', motif: 'Urgence familiale', justifie: true, preuve: 'Attestation sur l\'honneur' }] },
  ],
};
